[package]
name = "household-power"
version = "0.0.1"
authors = ["Michael Sproul <micsproul@gmail.com>"]

[dependencies]

xml-rs = "*"
serial = "*"
time = "*"
log = "*"

[dependencies.festivus_client]

git = "https://github.com/michaelsproul/festivus_client.git"
